In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder,LabelEncoder,StandardScaler,MinMaxScaler

In [2]:
#feature engineering er shobkichu onek short ah ekhane korlam column transformer diye..amra mainly ei process ei korbo..learning purpose ah aage bhenge bhenge shikhsi.

df = pd.read_csv('titanic_data_updated.csv')
df

     PassengerId Survived  Pclass  ...     Fare Cabin  Embarked
0              1       no   third  ...   7.2500   NaN         S
1              2      yes   first  ...  71.2833   C85         C
2              3      yes   third  ...   7.9250   NaN         S
3              4      yes   first  ...  53.1000  C123         S
4              5       no   third  ...   8.0500   NaN         S
..           ...      ...     ...  ...      ...   ...       ...
886          887       no  second  ...  13.0000   NaN         S
887          888      yes   first  ...  30.0000   B42         S
888          889       no   third  ...  23.4500   NaN         S
889          890      yes   first  ...  30.0000  C148         C
890          891       no   third  ...   7.7500   NaN         Q

[891 rows x 12 columns]

### Splitting Data

In [3]:
df.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)

# family_size creation
#SibSp= SiblingSpouse and Parch=ParentChildren
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

#feature and target extract
X = df.drop(['Survived'],axis=1)
y = df['Survived']


X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

### Imputation of Data

In [5]:
imputer_transformer = ColumnTransformer(
    transformers=[
        ('age',SimpleImputer(missing_values=np.nan , strategy='mean'),['Age']), # list of tuple.(name(can give any name),class,column name)
        ('embarked',SimpleImputer(missing_values=np.nan , strategy='most_frequent'),['Embarked']),
        ('cabin',SimpleImputer(missing_values=np.nan , strategy='constant',fill_value='Missing',add_indicator=True),['Cabin'])
    ],
    remainder='passthrough',
    verbose_feature_names_out = False
)
imputer_transformer.set_output(transform='pandas')

imputer_transformer.fit(X_train)

X_train = imputer_transformer.transform(X_train)
X_test = imputer_transformer.transform(X_test)

### Outlier Handling of Age

In [9]:
mean_of_age = X_train['Age'].mean()
std_of_age = X_train['Age'].std()
X_train['zscore_Age'] = (X_train['Age']-mean_of_age)/std_of_age

X_train = X_train[abs(X_train['zscore_Age']) <=3]
X_train.drop(['zscore_Age'],axis=1 , inplace=True)

/var/folders/n9/zntydnf54wn0nll65r9v5kww0000gn/T/ipykernel_2910/1394070844.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train.drop(['zscore_Age'],axis=1 , inplace=True)

### Outlier Handling of Fare

In [10]:
fare_Q1 = X_train['Fare'].quantile(0.25)
fare_Q3 = X_train['Fare'].quantile(0.75)
fare_IQR = fare_Q3 - fare_Q1
fare_minimum = max(0,fare_Q1 - 1.5 * fare_IQR)
fare_maximum = fare_Q3 + 1.5 * fare_IQR

X_train['Fare']= X_train['Fare'].clip(fare_minimum , fare_maximum)

/var/folders/n9/zntydnf54wn0nll65r9v5kww0000gn/T/ipykernel_2910/2596566179.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Fare']= X_train['Fare'].clip(fare_minimum , fare_maximum)

### Encoding and Scaling

In [11]:
X_train['Cabin_Deck'] = X_train['Cabin'].astype(str).str[0]
X_test['Cabin_Deck'] = X_test['Cabin'].astype(str).str[0]

/var/folders/n9/zntydnf54wn0nll65r9v5kww0000gn/T/ipykernel_2910/938491672.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Cabin_Deck'] = X_train['Cabin'].astype(str).str[0]

In [13]:
encoder_scaler = ColumnTransformer(
    transformers=[
        ('pclass',OrdinalEncoder(categories=[['third','second','first']]),['Pclass']),
        ('embarked_sex',OneHotEncoder(sparse_output=False,drop='first'),['Embarked','Sex','Cabin_Deck']),
        ('age_scaler',StandardScaler(),['Age']),
        ('fare_scaler',MinMaxScaler(),['Fare','FamilySize'])
    ],
    remainder='passthrough',
    verbose_feature_names_out = False
)
encoder_scaler.set_output(transform='pandas') # by default numpy teh provide kore

encoder_scaler.fit(X_train)

X_train = encoder_scaler.transform(X_train)
X_test = encoder_scaler.transform(X_test)

In [15]:
X_train.drop(['Cabin','SibSp','Parch'],axis=1,inplace=True)
X_test.drop(['Cabin','SibSp','Parch'],axis=1,inplace=True)

In [16]:
### Final Dataset

In [17]:
X_train

     Pclass  Embarked_Q  ...  FamilySize  missingindicator_Cabin
331     2.0         0.0  ...         0.0                   False
733     1.0         0.0  ...         0.0                    True
382     0.0         0.0  ...         0.0                    True
704     0.0         0.0  ...         0.1                    True
813     0.0         0.0  ...         0.6                    True
..      ...         ...  ...         ...                     ...
106     0.0         0.0  ...         0.0                    True
270     2.0         0.0  ...         0.0                    True
860     0.0         0.0  ...         0.2                    True
435     2.0         0.0  ...         0.3                   False
102     2.0         0.0  ...         0.1                   False

[707 rows x 16 columns]

In [18]:
X_test

     Pclass  Embarked_Q  ...  FamilySize  missingindicator_Cabin
709     0.0         0.0  ...         0.2                    True
439     1.0         0.0  ...         0.0                    True
840     0.0         0.0  ...         0.0                    True
720     1.0         0.0  ...         0.1                    True
39      0.0         0.0  ...         0.1                    True
..      ...         ...  ...         ...                     ...
433     0.0         0.0  ...         0.0                    True
773     0.0         0.0  ...         0.0                    True
25      0.0         0.0  ...         0.6                    True
84      1.0         0.0  ...         0.0                    True
10      0.0         0.0  ...         0.2                   False

[179 rows x 16 columns]