Function

In [1]:
def welcome_message():
    print("Hello Bangladesh")
welcome_message()

Hello Bangladesh

In [4]:
#parameter
def welcome_message(user1,user2="Dibya"):
    print(f"Hello {user1} {user2}")
welcome_message("Dibya", "Jyoti")    
welcome_message("Dibya")

Hello Dibya Jyoti
Hello Dibya Dibya

In [1]:
#return and docstring
def adding(a,b):
    """
       add a & b
       a-> int
       b-> int
    """
    sum=a+b
    return sum
m= adding(4,7)
print(m)

11

In [7]:
help(adding) # it is called docstring

Help on function adding in module __main__:

adding(a, b)
    add a & b
    a-> int
    b-> int

In [8]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

Arguments

In [9]:
# positional arguments

def values(a, b, c):
    print(f"{a},{b},{c}")
values(10,20,30)

10,20,30

In [10]:
def values(*args):
    print(args)
values(10,20,30)

(10, 20, 30)

In [12]:
def values(*args):
    for i in args:
        print(i)
values(10,20,30)

10
20
30

In [13]:
# keyword arguments
def values(a, b, c):
    print(f"{a},{b},{c}")
values(a=10,c=30,b=20)

10,20,30

In [14]:
def values(**kwards):
    print(kwards)
values(a=10,b=20,c=30)

{'a': 10, 'b': 20, 'c': 30}

In [16]:
def values(**kwards):
    for key,value in kwards.items():
        print(f"{key}:{value}")
values(a=20,c=50,b=25)

a:20
c:50
b:25

Return Type

In [18]:
def welcome_message():
    print("Hello Bangladesh")
print(type(welcome_message()))

Hello Bangladesh
<class 'NoneType'>

In [19]:
def adding(a,b):
   
    sum=a+b
    return sum
print(type(adding(4,7)))

<class 'int'>

In [20]:
def adding(a,b):
   
    sum=a+b
    return sum
print(type(adding(4.7,7)))

<class 'float'>

In [22]:
def welcome_message(user="None"):
    return f"Hello {user}"
print(type(welcome_message()))

<class 'str'>

In [1]:
def adding(a,b):
    return a,b # type tuple
    #return [a,b] # type list

print(type(adding(4,7)))


### unzip

x,y=adding(4,7)
print(x,y)

<class 'tuple'>
4 7

Iterator

In [2]:
s={10,20,30,40,50}
# set ah index number er through teh value pawa jaay nah. tai iterator use kora hoy

s_iter=iter(s)
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))

print("You can do it by for loop also")

for i in s:
    print(i)

50
20
40
10
30
You can do it by for loop also
50
20
40
10
30

Generator

In [35]:
lst=[x for x in range(500)] #dataset and eta create korar jonno comprehension use korsi
#print(lst)

def data_loader(chunk_size,lst):
    for i in range(0,len(lst), chunk_size):
        yield lst[i:i+chunk_size] 
x=data_loader(5,lst)
print(next(x))
print(next(x))

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]

Lambda, Map and Apply function

In [40]:
import pandas as pd


df = pd.DataFrame({'temperature (F)': [32, 212, 98.6, 68]})

df
df['temperature (C)'] = df['temperature (F)'].apply(lambda x: (x - 32) * 5/9)
df

   temperature (F)  temperature (C)
0             32.0              0.0
1            212.0            100.0
2             98.6             37.0
3             68.0             20.0

In [42]:
import pandas as pd


df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [5, 6, 7, 8]})

df

df['A'] = df['A'].apply(lambda x: x ** 0.5)

print(df) # print df lekha or sudhu df lekha ekhane same.duita tei print hobe

          A  B
0  1.000000  5
1  1.414214  6
2  1.732051  7
3  2.000000  8

In [43]:
import pandas as pd

df = pd.DataFrame({'total_spent': [120, 600, 450, 800]})

# Creating a 'High Value' feature on the fly
df['is_high_value'] = df['total_spent'].apply(lambda x: 1 if x > 500 else 0)

df

   total_spent  is_high_value
0          120              0
1          600              1
2          450              0
3          800              1

In [3]:
import pandas as pd
# apply and map kind of same kaaj e kore

df = pd.DataFrame({'total_spent': [120, 600, 450, 800]})

# Creating a 'High Value' feature on the fly
df['is_high_value'] = df['total_spent'].map(lambda x: 1 if x > 500 else 0)

df

   total_spent  is_high_value
0          120              0
1          600              1
2          450              0
3          800              1